name: Ping Render

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
    - name: Ping API
      run: curl https://kairos-handmade.onrender.com/api/v1/health
